name: pypruning
channels:
  - conda-forge
  - gurobi
dependencies:
  - python=3.8
  - numpy
  - pylint
  - scikit-learn
  - pip
  - pandas
  - setuptools
  - matplotlib
  - jupyter
  - tqdm
  - gurobi
  - pdoc3
  - pip:
    - cvxpy
    # - cvxopt
    - -e file:.