name: pypruning
channels:
  - conda-forge
  - gurobi
dependencies:
  - python=3.8
  - numpy
  - pylint
  - scikit-learn
  - pandas
  - setuptools
  - tqdm
  - gurobi
  - sphinx
  #- argparse
  - pip
  - pip:
    - karma-sphinx-theme
    - sphinx_rtd_theme
    - cvxpy
    - cvxopt
    - -e file:.